defaults:
  - inference_base
  - _self_

run_name_: ucond_200M_tri
ckpt_path: ./checkpoints/
ckpt_name: proteina_v1.1_DFS_200M_tri.ckpt

self_cond: False

sampling_caflow:
  sampling_mode: vf  # "vf" for ODE sampling, "sc" for SDE sampling
  sc_scale_noise: 0.0  # noise scale, used if sampling_mode == "sc"

nres_lens: [200]
max_nsamples: 6
